/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Import */
        post: operations["create_import_api_v1_datasets_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Quality */
        get: operations["dataset_quality_api_v1_datasets__dataset_id__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Dataset */
        post: operations["publish_dataset_api_v1_datasets__dataset_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Dataset */
        post: operations["activate_dataset_api_v1_datasets__dataset_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filters */
        get: operations["filters_api_v1_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Overview */
        get: operations["dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Trends */
        get: operations["dashboard_trends_api_v1_dashboard_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/furnaces/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranking */
        get: operations["ranking_api_v1_furnaces_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/furnaces/{furnace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Furnace */
        get: operations["furnace_api_v1_furnaces__furnace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostic */
        get: operations["diagnostic_api_v1_diagnostics__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /**
         * Query Jobs
         * @description Return a bounded job batch for clients polling several background tasks.
         */
        post: operations["query_jobs_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_v1_exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_api_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_v1_exports__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_import_api_v1_datasets_imports_post */
        Body_create_import_api_v1_datasets_imports_post: {
            /** File */
            file: string;
            /**
             * Kind
             * @default temporary
             * @enum {string}
             */
            kind: "shared" | "temporary";
            /** Name */
            name?: string | null;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "shared" | "temporary";
            /** Status */
            status: string;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Published At */
            published_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Row Count */
            row_count: number;
            /** Valid Production Count */
            valid_production_count: number;
            /** Furnace Count */
            furnace_count: number;
            /** Date Min */
            date_min?: string | null;
            /** Date Max */
            date_max?: string | null;
            /** Quality Status */
            quality_status: string;
            /** Complete Dates */
            complete_dates?: {
                [key: string]: string;
            };
            /** Coverage */
            coverage?: {
                [key: string]: unknown;
            };
        };
        /** ExportRequest */
        ExportRequest: {
            /** Dataset Id */
            dataset_id?: string | null;
            /**
             * Report Type
             * @enum {string}
             */
            report_type: "daily_summary" | "monthly_summary" | "furnace_stats" | "furnace_daily_trend" | "anomaly" | "fault_analysis" | "fault_warning" | "all";
            /** Production Lines */
            production_lines?: string[];
            /** Furnaces */
            furnaces?: string[];
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
        };
        /** FilterOptionsResponse */
        FilterOptionsResponse: {
            dataset: components["schemas"]["DatasetSummary"];
            scope: components["schemas"]["FilterScope"];
            /** Production Lines */
            production_lines?: string[];
            /** Furnaces */
            furnaces?: string[];
            /** Furnaces By Line */
            furnaces_by_line?: {
                [key: string]: string[];
            };
            /** Date Min */
            date_min?: string | null;
            /** Date Max */
            date_max?: string | null;
            /** Complete Dates */
            complete_dates?: {
                [key: string]: string;
            };
        };
        /** FilterScope */
        FilterScope: {
            /** Dataset Id */
            dataset_id?: string | null;
            /**
             * Grain
             * @default shift
             * @enum {string}
             */
            grain: "shift" | "furnace_day";
            /** Production Lines */
            production_lines?: string[];
            /** Furnaces */
            furnaces?: string[];
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportAccepted */
        ImportAccepted: {
            /** Job Id */
            job_id: string;
            /** Dataset Id */
            dataset_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** JobQueryRequest */
        JobQueryRequest: {
            /** Ids */
            ids: string[];
        };
        /** JobStatus */
        JobStatus: {
            /** Id */
            id: string;
            /** Job Type */
            job_type: string;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            };
            /** Error Code */
            error_code?: string | null;
            /** Error Detail */
            error_detail?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** KpiValue */
        KpiValue: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number | null;
            /**
             * Unit
             * @default
             */
            unit: string;
            /** Previous Value */
            previous_value?: number | null;
            /** Delta Percent */
            delta_percent?: number | null;
        };
        /** LineSnapshot */
        LineSnapshot: {
            /** Production Line */
            production_line: string;
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Is Confirmed Complete */
            is_confirmed_complete: boolean;
            /** Kpis */
            kpis: components["schemas"]["KpiValue"][];
            /** Active Furnaces */
            active_furnaces: number;
            /** Serious Alerts */
            serious_alerts: number;
            /** Pairing Completeness */
            pairing_completeness: number;
            /** Freshness Days */
            freshness_days: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            dataset: components["schemas"]["DatasetSummary"];
            /** Line Snapshots */
            line_snapshots: components["schemas"]["LineSnapshot"][];
            /** Common Comparison Date */
            common_comparison_date?: string | null;
            /** Quality Issue Counts */
            quality_issue_counts?: {
                [key: string]: number;
            };
            /** Top Risks */
            top_risks?: {
                [key: string]: unknown;
            }[];
        };
        /** PublishRequest */
        PublishRequest: {
            /** Confirm */
            confirm: boolean;
            /** Complete Dates */
            complete_dates?: {
                [key: string]: string;
            };
            /** Acknowledged Issue Codes */
            acknowledged_issue_codes?: string[];
        };
        /** QualityIssueBody */
        QualityIssueBody: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low" | "info";
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Affected Count */
            affected_count: number;
            /** Affected Rate */
            affected_rate: number;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** QualityReport */
        QualityReport: {
            dataset: components["schemas"]["DatasetSummary"];
            /** Issues */
            issues: components["schemas"]["QualityIssueBody"][];
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Grain */
            grain: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_import_api_v1_datasets_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_api_v1_datasets_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_quality_api_v1_datasets__dataset_id__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_dataset_api_v1_datasets__dataset_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_dataset_api_v1_datasets__dataset_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filters_api_v1_filters_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                grain?: "shift" | "furnace_day";
                production_lines?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_trends_api_v1_dashboard_trends_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                grain?: "shift" | "furnace_day";
                production_lines?: string | null;
                furnaces?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ranking_api_v1_furnaces_ranking_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                grain?: "shift" | "furnace_day";
                production_lines?: string | null;
                furnaces?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                metric?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    furnace_api_v1_furnaces__furnace_id__get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                grain?: "shift" | "furnace_day";
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                furnace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostic_api_v1_diagnostics__kind__get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                grain?: "shift" | "furnace_day";
                production_lines?: string | null;
                furnaces?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_jobs_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_api_v1_exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_export_api_v1_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_v1_exports__export_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
